version: '3.4'

services:
  azureclicredentialcontainer:
    image: azureclicredentialcontainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
