version: '3.4'

services:
  azureclicredentialcontainer:
    image: jongio/azureclicredentialcontainer
    volumes: 
      - "${HOME}/.azure:/root/.azure"
    build:
      context: .
      dockerfile: Dockerfile