apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: azureclicredentialcontainer
  name: azureclicredentialcontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: azureclicredentialcontainer
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: azureclicredentialcontainer
    spec:
      containers:
        - image: jongio/azureclicredentialcontainer
          imagePullPolicy: "IfNotPresent"
          name: azureclicredentialcontainer
          resources: {}
          volumeMounts:
            - mountPath: /root/.azure
              name: cli
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - hostPath:
            path: /run/desktop/mnt/host/wsl/.azure
            type: Directory
          name: cli
          
status: {}
